# 路径
[Path]
trainDataPath = /mnt/e/Sign-Language-Recognition-ZN/data/video/train
validDataPath = /mnt/e/Sign-Language-Recognition-ZN/data/video/dev
testDataPath = /mnt/e/Sign-Language-Recognition-ZN/data/video/test
trainLabelPath = /mnt/e/Sign-Language-Recognition-ZN/CE-CSL/label/train.csv
validLabelPath = /mnt/e/Sign-Language-Recognition-ZN/CE-CSL/label/dev.csv
testLabelPath = /mnt/e/Sign-Language-Recognition-ZN/CE-CSL/label/test.csv
bestModuleSavePath = module/best.pth
currentModuleSavePath = module/current.pth

# 参数
[Params]
device = "cuda"
hiddenSize = 1024
lr = 0.0001
batchSize = 2
numWorkers = 8
pinmMemory = 1
moduleChoice = TFNet
dataSetName = CE-CSL