# 路径
[Path]
trainDataPath = ./data/video/train
validDataPath = ./data/video/dev
testDataPath = ./data/video/test
trainLabelPath = ./CE-CSL/label/train.csv
validLabelPath = ./CE-CSL/label/dev.csv
testLabelPath = ./CE-CSL/label/test.csv
bestModuleSavePath = module/best.pth
currentModuleSavePath = module/current.pth

# 参数
[Params]
device = cuda
hiddenSize = 1024
lr = 0.0001
batchSize = 1
numWorkers = 1
pinMemory = 1
moduleChoice = TFNet
dataSetName = CE-CSL